### ISSUE TITLE
Can it be used in gulp?

### ISSUE THREAD

**Issue by gerardcarbo** [Bartvds/eslint-path-formatter#2]
I have installed it with:

`npm install eslint-path-formatter --save-dev`

I've tried to use it in a gulp task as follow:

```
gulp.task('eslint', function () {
    gulp.src(['bin/**/*.js','server/**/*.js'])
        .pipe(eslint())
        .pipe(eslint.format('eslint-path-formatter'));
}); 
```

But it fails with the error:

```
TypeError: Invalid Formatter
    at Object.exports.resolveFormatter (...\node_modules\gulp-eslint\util.js:129:10)
    at Function.gulpEslint.format (...\node_modules\gulp-eslint\index.js:113:19)
    at Gulp.<anonymous> (...\gulpfile.js:39:22)
```

**Comment by gerardcarbo** [comment]
I've make it work. Just specify the path:

```
.pipe(eslint.format('node_modules/eslint-path-formatter'));
```
