### ISSUE TITLE
config undefined error

### ISSUE THREAD

**Issue by Morriz** [Bartvds/eslint-path-formatter#3]
Hi, if I use your formatter (0.1.1) as is with node 0.12.7 I get the following error:

```
TypeError: Cannot read property 'rules' of undefined
    at module.exports (.../node_modules/eslint-path-formatter/index.js:118:20)
    at printResults (.../node_modules/eslint/lib/cli.js:79:14)
    at Object.cli.execute (.../node_modules/eslint/lib/cli.js:170:17)
    at Object.<anonymous> (.../node_modules/eslint/bin/eslint.js:61:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by a-x-** [comment]
I have a similar issue with latest eslint and node:
```
Cannot read property 'rules' of undefined
TypeError: Cannot read property 'rules' of undefined
    at module.exports (/Users/mxtnr/rocket/felix/frontend/projects/admin/node_modules/eslint-path-formatter/index.js:118:21)
    at printResults (/Users/mxtnr/rocket/felix/frontend/projects/admin/node_modules/eslint/lib/cli.js:91:20)
    at Object.execute (/Users/mxtnr/rocket/felix/frontend/projects/admin/node_modules/eslint/lib/cli.js:201:17)
    at Object.<anonymous> (/Users/mxtnr/rocket/felix/frontend/projects/admin/node_modules/eslint/bin/eslint.js:74:28)
```

As I understand plugin is outdated and is not maintaining any more

**Comment by a-x-** [comment]
As I can see,
issue with rules was [fixed], but version did not bumped 🤦‍♀️

[fixed]: https://github.com/Bartvds/eslint-path-formatter/pull/1
